apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: overwrite
  namespace: ns2
spec:
  podSelector: {}
  egress:
    - to: 
      - namespaceSelector:
          matchLabels:
            name: ns1
      - namespaceSelector:
          matchLabels:
            name: ns2
  policyTypes:
  - Egress
