apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-client
  labels:
    app: iperf-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-client
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      containers:
      - name: iperf-client
        image: namnx228/k8s-multitenancy-iperf-amd64
        command:
          - bash
          - "-c"
          - "iperf -c iperf-service -t 2 -p 5000 && sleep 3600"
        imagePullPolicy: IfNotPresent

