apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: get_GNP_binding
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  namespace: ns1
  # apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: get-GNP
  apiGroup: rbac.authorization.k8s.io
