apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool1
spec:
  cidr: 172.16.0.0/28
  blockSize: 29
  ipipMode: Always
  natOutgoing: false # To solve internal dns problem
  # natOutgoing: true

---


apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool2
spec:
  cidr: 172.16.1.0/28
  blockSize: 29
  ipipMode: Always
  natOutgoing: true # Keep like this to test
