apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool1
spec:
  cidr: 172.16.0.0/28
  blockSize: 29
  ipipMode: Always
  natOutgoing: true # If false --> No internet access for pod in this namespace
---


apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pool2
spec:
  cidr: 172.16.1.0/28
  blockSize: 29
  ipipMode: Always
  natOutgoing: true 
