apiVersion: v1
kind: Pod
metadata:
  name: attacker
  labels:
    env: test
spec:
  # shareProcessNamespace: true # To share the host PID space
  containers:
  - name: attacker
    image: docker.io/namnx228/k8s-evaluation-security-attacker-amd64
    imagePullPolicy: Always
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /hosts/proc/
      name: proc-node-1

    securityContext:
      privileged: true # ---> Root permission
      # capabilities:
      #   add:
      #   - SYS_PTRACE
  nodeSelector:
      kubernetes.io/hostname: node-1
  restartPolicy: Always
  volumes:
  - name: proc-node-1
    hostPath: 
      path: /proc #----> mount the /proc file system
      type: Directory

