apiVersion: v1
kind: Pod
metadata:
  name: victim
  labels:
    env: test
spec:
  containers:
  - name: victim
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
      kubernetes.io/hostname: node-1
