apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: overwrite
  namespace: test2
spec:
  podSelector: {}
  egress:
    - to: 
      - namespaceSelector:
          matchLabels:
            name: test1
      - namespaceSelector:
          matchLabels:
            name: test2
  policyTypes:
  - Egress
