apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
spec:
  containers:
  - name: iperf-server
    image: namnx228/k8s-multitenancy-iperf-amd64
    command:
      - iperf
      - "-s"
      - "-p 5000"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

